module.exports =  [
    "front end",
    "back end",
    "java",
    "javascript",
    "python",
    "react",
    "sql",
    "php",
    ".net",
    "c#",
    "spring",
    "java-ee",
    "docker",
    "node.js",
    "kubernetes",
    "amazon web services",
    "c++",
    "cloud",
    "android",
    "go",
    "mysql",
    "angularjs",
    "agile",
    "linux",
    "scala",
    "ios",
    "kotlin",
    "typescript",
    "css",
    "microservices",
    "sysadmin",
    "testing",
    "ruby on rails",
    "swift",
    "postgresql",
    "ruby",
    "qa",
    "oracle",
    "mobile",
    "rest",
    "html",
    "asp.net",
    "security",
    "devops",
    "angular",
    "objective c",
    "automation",
    "spring mvc",
    "php",
    "1c",
    "seo",
    "devops",
    "salesforce",
    "sharepoint"
]